---
site_name: Switcher WebAPI
site_url: https://switcher-webapi.tomfi.info
site_author: Tomer Figenblat
site_description: Switcher WebAPI Documentation

repo_url: https://github.com/TomerFi/switcher_webapi
edit_uri: ""

copyright: Copyright &copy; 2022 Tomer Figenblat

markdown_extensions:
  - pymdownx.betterem
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  version: "1.2.1"
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/realTomFi
      name: realTomfi on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/TomerFi
      name: TomerFi on GitHub
    - icon: fontawesome/brands/dev
      link: https://dev.to/tomerfi
      name: tomerfi on Dev.to
    - icon: fontawesome/brands/redhat
      link: https://developers.redhat.com/author/tomerfi
      name: tomerfi on Red Hat Developer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tomerfi/
      name: tomerfi on LinkedIn

plugins:
  - git-revision-date
  - swagger-ui-tag

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  font:
    code: Fira Code
    text: Open Sans
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
