---
name: DockerTest

on:
  pull_request:
    branch: dev

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify docker image
    steps:
      - name: Source checkout
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error

      - name: Get current date
        id: getDate
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.2

      - name: Build docker image (no push)
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ steps.getDate.outputs.date }}
            VERSION=testing
          tags: tomerfi/switcher_webapi:testing

      - name: Test container structure
        uses: brpaz/structure-tests-action@v1.1.2
        with:
          image: tomerfi/switcher_webapi:testing
          configFile: container_structure.yml

      - name: Delete docker image
        run: docker image rm tomerfi/switcher_webapi:testing
